project_name: xinhari
release:
  github:
    owner: xinhari
    name: xinhari
  name_template: 'Release {{.Tag}}'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'