name: Docker

on:
  push:
    branches:
    - main
    tags:
    - v0.*
    - v1.*
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
         name: Check out repository
       - uses: elgohr/Publish-Docker-Github-Action@2.12
         name: Build and Push Docker Image
         with:
           name: xinhari/xinhari
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           tag_names: true