name: Build and test xinhari
on:
  push: 
    branches:
      - 'release-**'

jobs:

  build:
    name: Build and test xinhari
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out this code
      uses: actions/checkout@v2
      with:
        path: 'xinhari'

    - name: Check out hari
      uses: actions/checkout@v2
      with:
        repository: 'xinhari/hari'
        path: 'hari'

    - name: Build all
      run: $GITHUB_WORKSPACE/xinhari/.github/workflows/scripts/build-xinhari.sh $GITHUB_SHA
      working-directory: xinhari
    