name: Build all github.com/xinhari/examples
on:
  push: 
    branches:
      - 'release-**'

jobs:

  build:
    name: Build repos
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v1
      with:
        go-version: 1.18
      id: go

    - name: Check out this code
      uses: actions/checkout@v2
      with:
        path: 'xinhari'

    - name: Check out code examples
      uses: actions/checkout@v2
      with:
        repository: 'xinhari/examples'
        path: 'examples'

    - name: Build all
      run: $GITHUB_WORKSPACE/xinhari/.github/workflows/scripts/build-all-examples.sh $GITHUB_SHA
      working-directory: examples
    